CREATE TABLE IF NOT EXISTS request_records (
    id CHAR(32) PRIMARY KEY,
    owner_id INT NULL,
    username VARCHAR(64) NOT NULL DEFAULT '',
    role VARCHAR(16) NOT NULL DEFAULT 'guest',
    feature VARCHAR(24) NOT NULL,
    endpoint VARCHAR(100) NOT NULL,
    problem MEDIUMTEXT NOT NULL,
    has_image BOOLEAN NOT NULL DEFAULT FALSE,
    content_truncated BOOLEAN NOT NULL DEFAULT FALSE,
    device VARCHAR(40) NOT NULL DEFAULT '',
    status VARCHAR(24) NOT NULL DEFAULT 'processing',
    http_status SMALLINT NULL,
    duration_ms INT UNSIGNED NULL,
    job_id CHAR(32) NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX ix_requests_time(created_at,id),
    INDEX ix_requests_owner_time(owner_id,created_at,id),
    INDEX ix_requests_status_time(status,created_at,id),
    INDEX ix_requests_feature_time(feature,created_at,id),
    INDEX ix_requests_job(job_id),
    CONSTRAINT fk_request_owner FOREIGN KEY(owner_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
